server:
 port: 8080
spring:
  redis:
    port: 6379
    host: 192.168.31.95
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:xml/*